export default function updateAlias(str) {
    const name = str.toLowerCase();
    const alias = name
        .replace(/[^a-zа-яё\d\s.,-]/g, '')
        .replace(/а/g, 'a')
        .replace(/б/g, 'b')
        .replace(/в/g, 'v')
        .replace(/г/g, 'g')
        .replace(/д/g, 'd')
        .replace(/е/g, 'e')
        .replace(/ё/g, 'yo')
        .replace(/ж/g, 'j')
        .replace(/з/g, 'z')
        .replace(/и/g, 'i')
        .replace(/й/g, 'ij')
        .replace(/к/g, 'k')
        .replace(/л/g, 'l')
        .replace(/м/g, 'm')
        .replace(/н/g, 'n')
        .replace(/о/g, 'o')
        .replace(/п/g, 'p')
        .replace(/р/g, 'r')
        .replace(/с/g, 's')
        .replace(/т/g, 't')
        .replace(/у/g, 'u')
        .replace(/ф/g, 'f')
        .replace(/х/g, 'h')
        .replace(/ц/g, 'c')
        .replace(/ч/g, 'ch')
        .replace(/ш/g, 'sh')
        .replace(/щ/g, 'sch')
        .replace(/ъ/g, '')
        .replace(/ы/g, 'y')
        .replace(/ь/g, '')
        .replace(/э/g, 'e')
        .replace(/ю/g, 'u')
        .replace(/я/g, 'ya')
        .replace(/ /g, '-')
        .replace(/,/g, '-')
        .replace(/\./g, '-')
        .replace(/-/g, '-')
    return alias.replace(/-+/g, '-').replace(/(^-|-$)/g, '')
}
